### ISSUE TITLE
The bot auto disconnects from vc

### ISSUE THREAD

**Issue by Rstacx** [codebois-dev/bard#1]
When we /play add a song, it will connect to the voice channel and the song will be added to the queue. Once connected to the voice channel, the bot will disconnect from the voice channel. 

After searching and adding the song from the dashboard, it will happen here

**Comment by MaciejkaG** [comment]
That's a problem occurring with only some of the songs which is very weird. In my case (I use the bot on daily basis) Bard struggles to play 1h+ tracks especially. I'll look into it but seems like it's a problem with ``discord-player`` library or the ``play-dl`` package. 
### Temporary fixes you can try right now
- Restart the bot
- Try again later
Unluckily that must work for now. I will try contacting ``discord-player`` developers or look for fixes in their GitHub issues in order to resolve the problem.

**Comment by MaciejkaG** [comment]
Please try fetching the latest commit, reinstalling the modules and replacing this line in your ``.env``:
```DP_FORCE_YTDL_MOD="play-dl" # For compatibility purposes, don't modify```
with this:
```DP_FORCE_YTDL_MOD="ytdl-core" # For compatibility purposes, don't modify```

Tell me if you'd experience this bug again. If not, close this issue.
